package com.cape.lib.management.system.util;

public class QueryUtils {

    public static final String LIB_MGT_ADD_QUERY = "INSERT INTO BOOK(BOOK_NAME,BOOK_REF) VALUES(:BOOK_NAME,BOOK_REF);"+
            "INSERT INTO USER(FIRST_NAME,LAST_NAME) VALUES(:FIRST_NAME,LAST_NAME);" +
            "INSERT INTO PUBLISH(PUBLISH_ORG,PUBLISH_COUNTRY) VALUES(:PUBLISH_ORG,:PUBLISH_COUNTRY);" +
            "INSERT INTO AUTHOR(AUTH_FIRST_NAME,AUTH_LAST_NAME) VALUES(:AUTH_FIRST_NAME,AUTH_LAST_NAME);";

    public static final String LIB_MGT_UPDATE_QUERY = "UPDATE BOOK SET BOOK_NAME=:BOOK_NAME,BOOK_REF=:BOOK_REF WHERE BOOK_ID=:BOOK_ID;"+
            "UPDATE USER SET FIRST_NAME=:FIRST_NAME,LAST_NAME=:LAST_NAME WHERE BOOK_ID=:BOOK_ID;" +
            "UPDATE PUBLISH SET PUBLISH_ORG=:PUBLISH_ORG,PUBLISH_COUNTRY=:PUBLISH_COUNTRY WHERE BOOK_ID=:BOOK_ID;" +
            "UPDATE AUTHOR SET AUTH_FIRST_NAME=:AUTH_FIRST_NAME,AUTH_LAST_NAME=AUTH_LAST_NAME WHERE BOOK_ID=:BOOK_ID;";
    public static final String LIB_MGT_DELET_QUERY = "DELETE FROM BOOK WHERE BOOK_ID=:BOOK_ID";

    public static final String LIB_MGT_SEARCH_BY_QUERY = "SELECT * FROM BOOK " +
            "INNER JOIN AUTHOR ON AUTHOR.Author_name = :author " +
            "INNER JOIN PUBLISHER ON PUBLISHER.pulisher_name = :publishname " +
            "where BOOK.NAME = :name   and BOOK.CATEGOTRY= :category";
}
